name: "Create Explosion"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: make gradle wrapper executable
      run: chmod +x ./gradlew
    - name: build
      run: ./gradlew :server:build
    - name: capture build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Server
        path: server/build/libs/
        
  build-mirai:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: make gradle wrapper executable
      run: chmod +x ./gradlew
    - name: build
      run: ./gradlew :mirai:build
    - name: capture build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Mirai-Bot
        path: mirai/build/libs/

  build-omni:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew :omni:build
      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Omni
          path: omni/build/libs/
